encoder:
  type: 's3prl'
  upstream: 'wavlm_base_plus'
  avg_layer_features: true
  pooling: 'tdnn'
  frozen: true
method:
  type: 'supervised'
  nb_classes: 5994
trainer:
  epochs: 30
evaluation:
  validation:
    - type: 'sv_cosine'
  test:
    - type: 'sv_cosine'
      frame_length: null
dataset:
  train: 'voxceleb2_train.csv'
  augmentation:
    enable: true