encoder:
  type: 'ecapatdnn'
  channels: [1024, 1024, 1024, 1024, 1536]
  mel_n_mels: 80
method:
  type: 'supervised'
  nb_classes: 5994
trainer:
  optimizer: 'sgd'
  learning_rate: 0.2
  learning_rate_sched: 'warmup+cosine'
  weight_decay: 0.0001
evaluation:
  validation:
    - type: 'sv_cosine'
  test:
    - type: 'sv_cosine'
      frame_length: null
      score_norm: 'as-norm'
dataset:
  train: 'voxceleb2_train.csv'
  augmentation:
    enable: true
    strategy: 'reverb|noise'
    aug_prob: 0.6
