encoder:
  type: 'ecapatdnn'
  channels: [1024, 1024, 1024, 1024, 3072]
method:
  type: 'supervised'
  nb_classes: 5
  classifier: 'linear'
  freeze_encoder: true
trainer:
  init_weights: 'models/ssl/voxceleb2/simclr/simclr_enc-ECAPATDNN-1024_proj-none_t-0.03/checkpoints/model_avg.pt'
  epochs: 50
  tracked_metric: 'val/classification/cremad_train/accuracy'
  tracked_mode: 'max'
  learning_rate: 0.0001
evaluation:
  validation:
    - type: 'classification'
      csv: 'cremad_train.csv'
      key: 'Emotion'
  test:
    - type: 'classification'
      frame_length: null
      csv: 'cremad_train.csv'
      key: 'Emotion'
dataset:
  train: 'cremad_train.csv'
  label_key: 'Emotion'
  augmentation:
    enable: true
